spring:
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.yaml
    enabled: true
  jpa:
    database: h2
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

